name: 'Sonarqube Scanner w/ branch support'
description: 'Scan code using Sonarqube'
author: 'MindDoc GmbH'
inputs:
  app:
    description: 'Application name'
    required: true
  baseDir:
    description: 'Project base directory'
    required: true
  login:
    description: 'Sonar login string'
    required: true
  url:
    description: 'Sonar server url'
    required: true
  branchName:
    description: 'The branch this analysis is being ran against'
  pullRequestKey:
    description: 'The identifier for this PR'
  pullRequestBranch:
    description: 'The branch that contains the changes to be merged'
  pullRequestBase:
    description: 'The branch into which we shall be merging. Defaults to master if not set.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'blue'
